---
# ensures that we have ansible prereq packages
# for now, only known dependency is python2-dnf on Fedora, 
# I'll abstract this to a better solution if this becomes a problem
- raw: dnf -y install python2 python2-dnf libselinux-python
  become: True
  when: ansible_distribution == "Fedora"

- raw: pacman -S python2 python3
  become: True
  when: ansible_distribution == "Archlinux"
