---
# tasks file for emacs
- name: Install latest version of emacs
  package:
    name: emacs
    state: latest
  become: true
  tags: emacs

- name: Check for existing .spacemacs file
  stat: "path={{ ansible_env.HOME }}/.spacemacs"
  register: dotspacemacs
  tags: emacs

- name: Install spacemacs, delete the new .spacemacs file and symlink mine
  block:
  - git:
      repo: "https://github.com/syl20bnr/spacemacs"
      dest: "{{ ansible_env.HOME }}/.emacs.d"
      update: yes
            
  - file:
      path: "{{ ansible_env.HOME }}/.spacemacs"
      state: absent

  - name: Symlink .spacemacs
    file:
      src: "{{ ansible_env.HOME}}/dotfiles/.spacemacs"
      dest: "{{ ansible_env.HOME }}/.spacemacs"
      state: link

  when: dotspacemacs.stat.exists == false
  tags: emacs

# install Hasklig, unless this is ArchLinux - then just use the package
- name: Download and unzip Hasklig
  unarchive:
    src: "https://github.com/i-tu/Hasklig/releases/download/{{ hasklig_version }}/Hasklig-{{ hasklig_version }}.zip"
    dest: /usr/share/fonts
    remote_src: true
    creates: "/usr/share/fonts/Hasklig-{{ hasklig_version }}.zip"
  become: true
  vars: 
    hasklig_version: "1.1"
  when: ansible_distribution != "ArchLinux"
  tags: emacs

- name: Update font cache
  command: fc-cache
  when: ansible_distribution != "ArchLinux"
  tags: emacs
      

